name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.1.1'
      SERVERPOD_PASSWORD_database: 'iAL26Dz1hZMgWZtgq8tbmt8k5YhciZ1L'
      SERVERPOD_PASSWORD_redis: 'd3lCoyzjJBfCq4sCuk0jaUxt3BYgtSQU'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: pchaa_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: pchaa_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: pchaa_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: pchaa_server
        run: serverpod generate

      - name: Run tests
        working-directory: pchaa_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: pchaa_server
        run: docker compose down -v
